const BASE='https://autorace.jp';
export const VENUES={kawaguchi:{code:2,key:'KAWAGUCHI',name:'川口'},isesaki:{code:3,key:'ISESAKI',name:'伊勢崎'},hamamatsu:{code:4,key:'HAMAMATSU',name:'浜松'},iizuka:{code:5,key:'IIZUKA',name:'飯塚'},sanyou:{code:6,key:'SANYOU',name:'山陽'}};
const tokenOf=html=>html.match(/<meta\s+name=["']csrf-token["']\s+content=["']([^"']+)/i)?.[1]||null;
const cookieOf=response=>(response.headers.getSetCookie?.()||[response.headers.get('set-cookie')]).filter(Boolean).map(x=>x.split(';')[0]).join('; ');
export function createOfficialAutoClient({fetchImpl=fetch,baseUrl=BASE}={}){
  let token=null,cookie='';
  async function session(venue,date,raceNo){const url=`${baseUrl}/race_info/Program/${venue}/${date}_${raceNo}`,r=await fetchImpl(url);if(!r.ok)throw Error(`OFFICIAL_SESSION_HTTP_${r.status}`);const html=await r.text();token=tokenOf(html);cookie=cookieOf(r);if(!token)throw Error('OFFICIAL_CSRF_TOKEN_MISSING');return{url,status:r.status,bytes:Buffer.byteLength(html)}}
  async function post(path,params,{csrf=false}={}){const body=new URLSearchParams(Object.entries(params).map(([k,v])=>[k,String(v)]));const headers={'content-type':'application/x-www-form-urlencoded; charset=UTF-8','x-requested-with':'XMLHttpRequest'};if(csrf){headers['x-csrf-token']=token;headers.cookie=cookie;}const started=Date.now(),r=await fetchImpl(`${baseUrl}/race_info/${path}`,{method:'POST',headers,body});const text=await r.text();if(!r.ok)throw Error(`${path.toUpperCase()}_HTTP_${r.status}`);let value;try{value=JSON.parse(text)}catch{throw Error(`${path.toUpperCase()}_INVALID_JSON`)}if(value.result!=='Success')throw Error(`${path.toUpperCase()}_${value.result||'FAILURE'}`);return{body:value.body,httpStatus:r.status,bytes:Buffer.byteLength(text),latencyMs:Date.now()-started,endpoint:`${baseUrl}/race_info/${path}`};}
  return{async fetchRace({venue,date,raceNo}){const v=VENUES[venue];if(!v)throw Error('UNKNOWN_VENUE');const params={placeCode:v.code,raceDate:date,raceNo};const s=await session(venue,date,raceNo);const [program,info,result]=await Promise.all([post('Program',params,{csrf:true}),post('OtherRaceInfo',params),post('RaceResult',params)]);return{venue:v,date,raceNo,session:s,program,info,result};}};
}
