import crypto from 'node:crypto';
export const STAGES=['PRE','TRIAL_AVAILABLE','FINAL_PRE_RACE','RESULT_CONFIRMED'];
const iso=v=>v?new Date(v).toISOString():null,num=v=>v==null||v===''?null:Number(v),txt=v=>v==null||v===''?null:String(v),compactDate=d=>String(d).replace(/[^0-9]/g,'');
const TRACK_CONDITIONS={0:'良走路',1:'湿走路',2:'風',3:'オイル',4:'荒',5:'斑走路'},RACE_CLASSES={1:'予選',2:'選抜予選',3:'一般戦',4:'特別一般戦',5:'選抜戦',6:'特別選抜戦',7:'準々決勝戦',8:'準決勝戦',9:'優勝戦'};
export function autoRaceKey({date,venueKey,raceNo}){const d=compactDate(date),v=String(venueKey||'').toUpperCase(),r=Number(raceNo);if(!/^\d{8}$/.test(d)||!/[A-Z]+/.test(v)||!Number.isInteger(r)||r<1||r>12)throw Error('INVALID_AUTO_RACE_IDENTITY');return`${d}-AUTO-${v}-${r}`;}
export const canonical=value=>Array.isArray(value)?value.map(canonical):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(k=>[k,canonical(value[k])])):value;
export function sealSnapshot(value){const copy=structuredClone(value);delete copy.hash;copy.hash=crypto.createHash('sha256').update(JSON.stringify(canonical(copy))).digest('hex');return copy;}
export function verifySnapshotHash(value){return sealSnapshot(value).hash===value.hash;}
const missing=(field,reason)=>({field,reason});
function participant(p){return{riderId:txt(p.playerCode),registrationNo:txt(p.playerCode),riderName:txt(p.playerName),lane:num(p.carNo),carNo:num(p.carNo),handicap:num(p.handicap),class:txt(p.bikeClass),age:num(p.age),rank:txt(p.rank),graduationCode:txt(p.graduationCode),machineName:txt(p.bikeName),machineNo:null,trialTime:num(p.trialRunTime),trialRetry:p.trialRetryCode!=null,trialOrder:null,trialDeviationRaw:num(p.raceDev),publishedStartData:null,absence:p.absent??null,replacement:null,observedAt:null};}
function baseRace(raw){const i=raw.info.body,condition=num(i.situationCode);return{raceKey:autoRaceKey({date:raw.date,venueKey:raw.venue.key,raceNo:raw.raceNo}),date:raw.date,venue:raw.venue.name,venueCode:raw.venue.code,raceNo:Number(raw.raceNo),scheduledStart:i.raceStartTime?`${raw.date}T${i.raceStartTime}:00+09:00`:null,raceClass:RACE_CLASSES[num(i.classCode)]||null,raceTitle:txt(i.raceName),grade:txt(i.gradeName),distance:num(i.distance),laps:null,entryCount:(raw.program.body.playerList||[]).length,weather:txt(i.weather),temperature:num(i.temp),humidity:num(i.humid),windDirection:null,windSpeed:null,trackConditionCode:condition,trackCondition:TRACK_CONDITIONS[condition]||null,trackTemperature:num(i.roadtemp),trackMoisture:null,observedAt:null,source:'autorace.jp official public race_info',sourceVersion:'AUTO_OFFICIAL_JSON_V1'};}
function resultStatus(rows,refund){if(!rows.length)return'UNKNOWN';if((refund?.absent||[]).length)return'refund';if(rows.some(x=>x.accidentCode||x.foulCode))return'accident';return'normal';}
export function buildSnapshots(raw,{capturedAt=new Date().toISOString(),historicalReadback=true}={}){const race=baseRace(raw),participants=(raw.program.body.playerList||[]).map(participant),trials=participants.map(x=>x.trialTime).filter(Number.isFinite),common={schemaVersion:'AUTO_RACE_SNAPSHOT_V1',raceKey:race.raceKey,capturedAt:iso(capturedAt),sourceObservedAt:null,historicalReadback,source:'https://autorace.jp',sourceVersion:'AUTO_OFFICIAL_JSON_V1',race,participants,missing:[...(!race.laps?[missing('race.laps','OFFICIAL_SOURCE_NOT_EXPOSED')]:[]),...(!race.windDirection?[missing('race.windDirection','OFFICIAL_SOURCE_NOT_EXPOSED')]:[]),...(!race.trackMoisture?[missing('race.trackMoisture','OFFICIAL_SOURCE_NOT_EXPOSED')]:[])],rawReferences:{program:raw.program.endpoint,otherRaceInfo:raw.info.endpoint}};
  const pre=sealSnapshot({...common,stage:trials.length?'TRIAL_AVAILABLE':'PRE',derived:trials.length?{trialOrder:[...participants].filter(x=>Number.isFinite(x.trialTime)).sort((a,b)=>a.trialTime-b.trialTime||a.carNo-b.carNo).map((x,i)=>({carNo:x.carNo,order:i+1}))}:null,result:null});
  const rows=Array.isArray(raw.result.body.raceResult)?raw.result.body.raceResult:[],refund=raw.result.body.refundInfo||{},result={status:resultStatus(rows,refund),finishOrder:rows.filter(x=>Number.isFinite(Number(x.order))).sort((a,b)=>a.order-b.order).map(x=>Number(x.carNo)),participants:rows.map(x=>({finishOrder:num(x.order),carNo:num(x.carNo),riderId:txt(x.playerCode),riderName:txt(x.playerName),machineName:txt(x.motorcycleName),handicap:num(x.handicap),trialTime:num(x.traialTime),finishTime:num(x.raceTime),startTiming:num(x.st),accidentCode:txt(x.accidentCode),accidentName:txt(x.accidentName),violationCode:txt(x.foulCode)})),payout:refund,refund:refund.absent||[],resultObservedAt:null,officialConfirmedAt:null};
  const resultCondition=num(raw.info.body.raceSituationCode),confirmed=sealSnapshot({...common,stage:'RESULT_CONFIRMED',race:{...race,weather:txt(raw.info.body.raceWeather)||race.weather,temperature:num(raw.info.body.raceTemp),humidity:num(raw.info.body.raceHumid),trackTemperature:num(raw.info.body.raceRoadtemp),trackConditionCode:resultCondition,trackCondition:TRACK_CONDITIONS[resultCondition]||null},participants:[],result,missing:[...common.missing,...(!rows.length?[missing('result.finishOrder','OFFICIAL_RESULT_UNAVAILABLE')]:[])],rawReferences:{raceResult:raw.result.endpoint,otherRaceInfo:raw.info.endpoint}});
  return{pre,result:confirmed};}
export function validateSnapshot(v){const errors=[];if(v.schemaVersion!=='AUTO_RACE_SNAPSHOT_V1')errors.push('schemaVersion');if(!/^\d{8}-AUTO-[A-Z]+-(?:[1-9]|1[0-2])$/.test(v.raceKey||''))errors.push('raceKey');if(!STAGES.includes(v.stage))errors.push('stage');if(!v.capturedAt||!Number.isFinite(Date.parse(v.capturedAt)))errors.push('capturedAt');if(!v.race?.date||!v.race?.venue||!Number.isInteger(v.race?.raceNo))errors.push('requiredRaceFields');if(!Array.isArray(v.participants)||!Array.isArray(v.missing))errors.push('collections');if(v.stage!=='RESULT_CONFIRMED'&&v.participants.some(p=>!p.riderId||!p.riderName||!Number.isInteger(p.carNo)))errors.push('requiredParticipantFields');if(v.stage!=='RESULT_CONFIRMED'&&v.result!=null)errors.push('RESULT_LEAKAGE');if(v.stage==='RESULT_CONFIRMED'&&!v.result)errors.push('result');if(!verifySnapshotHash(v))errors.push('hash');return{valid:errors.length===0,errors};}
