export const TERMINAL_TRACE_SCHEMA="TERMINAL_DETAIL_TRACE_V1";

const finite=value=>value!==null&&value!==undefined&&value!==""&&Number.isFinite(Number(value));
const number=value=>finite(value)?Number(value):null;
const terminalId=order=>(order||[]).map(Number).slice(0,3).join("-");
const sign=value=>value==null?"UNKNOWN":value>0?"POSITIVE":value<0?"NEGATIVE":"NEUTRAL";

// This module is observation-only. It copies values already produced by the
// prediction/purchase engines and never feeds a value back into either engine.
export function buildTerminalDetailTrace({race,prediction,purchase,provenance,generatedAt=new Date().toISOString(),sourceType="PRODUCTION_BASELINE",shadowVariantId=null}){
  const terminals=[...(purchase?.terminals||[])];
  const scored=[...(prediction?.scored||[])];
  const evidenceTable={},riders=scored.map(rider=>{
    const refs=[];
    for(const target of ["first","second","third"]){
      for(const [index,row] of (rider?.scoreTrace?.[target]||[]).entries()){
        const id=`R${Number(rider.number)}:${target}:${index}:${String(row?.key||"UNKNOWN")}`;
        evidenceTable[id]={id,type:String(row?.key||"UNKNOWN"),target:"rider",targetId:Number(rider.number),position:target,rawInput:row?.value??null,weight:number(row?.weight),contribution:number(row?.contribution),support:number(row?.contribution)>=0,counter:number(row?.contribution)<0,sourceTimestamp:row?.sourceTimestamp||null,observationFreshness:row?.freshness||"UNKNOWN",unknown:row?.available===false};
        refs.push(id);
      }
    }
    return{number:Number(rider.number),id:rider.id||rider.registration||null,role:rider.role||null,roleScores:copyNumbers(rider.roleScores),relativeScore:number(rider.relativeScore??rider.score),scoreTraceEvidenceIds:refs};
  });
  const branches=Object.fromEntries((prediction?.branches||[]).map(branch=>[String(branch.id),{id:String(branch.id),label:branch.label||null,type:branch.branchType||null,score:number(branch.score),probability:number(branch.probability),primaryLineId:branch.primaryLineId||null,firstCandidates:(branch.firstCandidates||[]).map(String),initiativeState:branch.initiativeState||null,lineState:branch.lineState||null,otherLineSurvival:branch.otherLineSurvival||null,fourthCornerState:branch.fourthCornerState||null}]));
  const scenarioTable=Object.fromEntries(Object.entries(provenance?.scenarioProvenances||{}).map(([id,row])=>[id,{id,type:row?.scenarioType||row?.branchType||null,branchId:row?.branchId||null,score:number(row?.scenarioScore??row?.branchScore),support:number(row?.scenarioSupport),counterEvidence:number(row?.counterEvidence),relativeScore:number(row?.relativeScore??row?.probability),initiativeState:row?.initiativeState||null,lineState:row?.lineState||null,otherLineSurvival:row?.otherLineSurvival||null,fourthCornerState:row?.fourthCornerState||null,raw:row}]));
  const pairStats=new Map();
  for(const terminal of terminals){
    const key=(terminal.order||[]).slice(0,2).map(Number).join("-");
    const score=terminalFinalScore(terminal),row=pairStats.get(key)||{scores:[],terminals:[]};
    if(score!==null)row.scores.push(score);row.terminals.push(terminalId(terminal.order));pairStats.set(key,row);
  }
  const pairTable={};
  for(const [key,row] of pairStats){
    const [first,second]=key.split("-").map(Number),reverse=pairStats.get(`${second}-${first}`),sample=terminals.find(t=>(t.order||[]).slice(0,2).map(Number).join("-")===key),dominant=dominantContribution(sample),compat=sample?.conditionalEvaluation?.second||dominant?.conditionalEvaluation?.second||null,directionalScore=row.scores.length?Math.max(...row.scores):null,reverseScore=reverse?.scores?.length?Math.max(...reverse.scores):null;
    pairTable[key]={id:key,first,second,directionScore:directionalScore,reverseDirectionScore:reverseScore,directionDelta:directionalScore!==null&&reverseScore!==null?directionalScore-reverseScore:null,compatibilityScore:number(compat?.factor),compatibilityState:compat?.classification||"UNKNOWN",sameLineState:compat?.relationToFirst||"UNKNOWN",roleRelationship:compat?.roles||[],conditionalSecondScore:number(sample?.conditionalScores?.secondConditionalScore),evidenceIds:branchEvidenceIds(dominant,evidenceTable,key),terminalIds:row.terminals};
  }
  const branchContributionTable={};
  const terminalRows=terminals.map((terminal,index)=>{
    const order=(terminal.order||[]).map(Number).slice(0,3),id=terminalId(order),dominant=dominantContribution(terminal),pairId=order.slice(0,2).join("-"),samePair=terminals.filter(row=>(row.order||[]).slice(0,2).map(Number).join("-")===pairId).sort(compareTerminal),thirdRank=samePair.findIndex(row=>terminalId(row.order)===id)+1;
    const rawComponents=componentValues(terminal,dominant),sum=Object.values(rawComponents).filter(finite).reduce((a,b)=>a+Math.abs(Number(b)),0);
    let cumulative=0;const components=Object.fromEntries(Object.entries(rawComponents).map(([name,value])=>{const contribution=number(value);if(contribution!==null)cumulative+=contribution;return[name,{rawInput:contribution,contribution,sign:sign(contribution),normalizedContribution:sum&&finite(value)?Number(value)/sum:null,cumulativeResult:contribution===null?null:cumulative}]}));
    const branchContributionIds=(terminal.branchContributions||[]).map((row,i)=>{const key=`${id}:B${i}:${row.branchId||"UNKNOWN"}`;branchContributionTable[key]={id:key,terminalId:id,branchId:row.branchId||null,branchScore:number(row.branchScore),weightedScore:number(row.weightedScore),pathScore:number(row.pathScore),probability:number(row.probability),positionScores:copyNumbers(row.positionScores),decisionRatios:copyNumbers(row.decisionRatios),positionEvidence:row.positionEvidence||null};return key;});
    return{id,order,finishingOrder:order,finalScore:terminalFinalScore(terminal),probability:number(terminal.probability),rank:number(terminal.terminalGlobalRank??terminal.purchaseRank)??index+1,scenarioId:terminal.scenarioProvenanceId||null,branchId:terminal.dominantBranchId||terminal.branchId||dominant?.branchId||null,pairId,thirdRankWithinPair:thirdRank||null,firstTrace:{riderNumber:order[0],baseScore:number(terminal?.conditionalScores?.firstBaseScore),conditionalScore:number(terminal?.conditionalScores?.firstConditionalScore),positionScore:number(dominant?.positionScores?.first),evidenceIds:branchEvidenceIds(dominant,evidenceTable,`${id}:first`,"first")},secondTrace:{riderNumber:order[1],baseScore:number(terminal?.conditionalScores?.secondBaseScore),conditionalScore:number(terminal?.conditionalScores?.secondConditionalScore),pairDirectionScore:pairTable[pairId]?.directionScore??null,pairCompatibilityScore:pairTable[pairId]?.compatibilityScore??null,evidenceIds:branchEvidenceIds(dominant,evidenceTable,`${id}:second`,"second")},thirdTrace:{riderNumber:order[2],baseScore:number(terminal?.conditionalScores?.thirdBaseScore),conditionalScore:number(terminal?.conditionalScores?.thirdConditionalScore),lineRelation:terminal?.conditionalEvaluation?.third?.relationToFirst||dominant?.conditionalEvaluation?.third?.relationToFirst||"UNKNOWN",roleRelation:terminal?.conditionalEvaluation?.third?.roles||dominant?.conditionalEvaluation?.third?.roles||[],scenarioCompatibility:number(terminal?.conditionalEvaluation?.third?.factor??dominant?.conditionalEvaluation?.third?.factor),rankWithinPair:thirdRank||null,evidenceIds:branchEvidenceIds(dominant,evidenceTable,`${id}:third`,"third")},scenarioTrace:{score:number(dominant?.branchScore),support:number(terminal.scenarioFamilySupport??terminal.branchContributions?.length),counterEvidence:number(terminal.relativeConditionPenalty),relativeScore:number(terminal.scenarioFamilyProbability??dominant?.probability),rank:number(terminal.scenarioFamilyRank??terminal.branchRank)},components,branchContributionIds,purchaseObservation:{status:terminal.purchaseStatus||null,rejectCode:terminal.purchaseRejectCode||null,betClass:terminal.betClass||null}};
  });
  return{schemaVersion:TERMINAL_TRACE_SCHEMA,sourceType,shadowVariantId:sourceType==="PRODUCTION_BASELINE"?null:shadowVariantId,raceKey:race?.raceKey||race?.id||null,predictionSnapshotId:null,predictionHash:null,generationTimestamp:generatedAt,resultDataUsed:false,immutablePredictionObservation:true,terminalCount:terminalRows.length,riders,marks:buildMarks(scored),lines:(prediction?.lines||[]).map(line=>({id:line.id||null,type:line.type||null,members:(line.members||[]).map(member=>Number(member.number||member.id)).filter(Number.isFinite)})),branches,scenarioTable,pairTable,evidenceTable,branchContributionTable,terminals:terminalRows,rankComparison:{rankedTerminalIds:[...terminalRows].sort((a,b)=>a.rank-b.rank||String(a.id).localeCompare(String(b.id))).map(row=>row.id),top10TerminalIds:[...terminalRows].sort((a,b)=>a.rank-b.rank).slice(0,10).map(row=>row.id)}};
}

function dominantContribution(terminal){return[...(terminal?.branchContributions||[])].sort((a,b)=>(Number(b.probability)||0)-(Number(a.probability)||0))[0]||null;}
function terminalFinalScore(row){return number(row?.terminalScore??row?.score??row?.probability);}
function compareTerminal(a,b){return (number(b?.terminalScore??b?.score)??-Infinity)-(number(a?.terminalScore??a?.score)??-Infinity)||terminalId(a.order).localeCompare(terminalId(b.order));}
function copyNumbers(value={}){return Object.fromEntries(Object.entries(value||{}).map(([key,item])=>[key,number(item)]));}
function componentValues(terminal,dominant){return{FIRST_RIDER_SCORE:number(dominant?.positionScores?.first??terminal?.conditionalScores?.firstConditionalScore),SECOND_CONDITIONAL:number(terminal?.conditionalScores?.secondConditionalScore??dominant?.positionScores?.second),PAIR_DIRECTION:number(terminal?.pairNaturalConvergenceScore??terminal?.pairScenarioCoherence),PAIR_COMPATIBILITY:number(terminal?.conditionalEvaluation?.second?.factor??dominant?.conditionalEvaluation?.second?.factor),THIRD_CONDITIONAL:number(terminal?.conditionalScores?.thirdConditionalScore??dominant?.positionScores?.third),SCENARIO_SCORE:number(dominant?.branchScore),SCENARIO_SUPPORT:number(terminal?.scenarioFamilySupport??terminal?.branchContributions?.length),COUNTER_EVIDENCE:number(terminal?.relativeConditionPenalty),LINE_ROLE:number(terminal?.naturalConvergenceScore),POSITION_FOURTH_CORNER:number(terminal?.relativeProbability),TERMINAL_RELATIVE_SCORE:number(terminal?.terminalScore)};}
function branchEvidenceIds(contribution,table,prefix,target=null){const rows=target?[contribution?.positionEvidence?.[target]]:Object.values(contribution?.positionEvidence||{});const ids=[];for(const [index,row] of rows.filter(Boolean).entries()){const id=`B:${prefix}:${target||row.target||index}`;if(!table[id])table[id]={id,type:"POSITION_EVIDENCE",target:target||row.target||"pair",targetId:row.number??prefix,rawInput:row.drivers||null,contribution:number(row.roleScore),support:true,counter:false,sourceTimestamp:null,observationFreshness:"UNKNOWN",unknown:false};ids.push(id);}return ids;}
function buildMarks(scored){const symbols=["◎","○","▲","△","☆"];return[...scored].sort((a,b)=>(Number(b?.roleScores?.first)||-Infinity)-(Number(a?.roleScores?.first)||-Infinity)||Number(a.number)-Number(b.number)).slice(0,5).map((row,index)=>({number:Number(row.number),mark:symbols[index],score:number(row?.roleScores?.first),source:"prediction.scored.roleScores.first"}));}

export function compareExactTerminalToTop10(trace,finishOrder){const id=terminalId(finishOrder),byId=new Map((trace?.terminals||[]).map(row=>[row.id,row])),exact=byId.get(id);if(!exact)return{status:"UNKNOWN",reason:"EXACT_TERMINAL_NOT_CAPTURED"};const top=(trace.rankComparison?.top10TerminalIds||[]).map(key=>byId.get(key)).filter(Boolean),componentNames=new Set([...(Object.keys(exact.components||{})),...top.flatMap(row=>Object.keys(row.components||{}))]);return{status:"AVAILABLE",exactTerminalId:id,exactRank:exact.rank,exactScore:exact.finalScore,top10:top.map(row=>({terminalId:row.id,rank:row.rank,scoreGap:number(row.finalScore)-number(exact.finalScore),componentGaps:Object.fromEntries([...componentNames].map(name=>[name,(number(row.components?.[name]?.contribution)||0)-(number(exact.components?.[name]?.contribution)||0)]))}))};}

