import {filterRaces,nextPendingRace,raceDate,searchQuery} from './ui-helpers.mjs';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let pending=true,allRows=[],rows=[],current=null,nextOffset=null;
$('reviewer').value=localStorage.getItem('action-reviewer')||'';const reviewer=()=>$('reviewer').value.trim();async function api(url,options){const r=await fetch(url,options),b=await r.json();if(!r.ok)throw Error(b.error==='INDEPENDENT_EVIDENCE_REQUIRED'?'映像など独立した根拠を確認した場合のみ保存できます。':b.error||r.status);return b}const notify=x=>$('message').textContent=x?.message||x||'';
async function status(){const {v2Progress:p,collector}=await api(`/api/status?reviewer=${encodeURIComponent(reviewer())}`);$('connection').textContent=`自動接続：${collector.lastError?'要確認':'稼働'} / 待機 ${collector.queueDepth}`;const rate=(p.progressRate*100).toFixed(1);$('coverage').innerHTML=[['収集総数',p.collectedRaces],['V2確認済み',p.confirmed],['V2未確認',p.pending],['レビュー不能',p.unavailable],['レビュー進捗',`${p.confirmed} / ${p.reviewTarget}（${rate}%）`],['UNKNOWN含む / 男子 / ガールズ',`${p.unknownReviewed} / ${p.maleConfirmed} / ${p.girlsConfirmed}`]].map(([l,v])=>`<div class="stat"><span>${l}</span><b>${v}</b></div>`).join('');$('details').innerHTML='<p>レビュー不能は未確認数とレビュー対象母数から除外されています。</p>'}
function renderList(){rows=filterRaces(allRows,$('period').value);const groups=new Map();for(const r of rows){const k=`${r.date}|${r.venue}`;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r)}$('races').innerHTML=[...groups].map(([k,rs])=>{const[d,v]=k.split('|');return`<details class="date-group" open><summary>${raceDate(d)}　${esc(v)}</summary>${rs.map(r=>`<button data-race="${esc(r.raceKey)}"><b>${r.raceNo}R</b><span>${r.girls?'ガールズ / ':''}${r.availability==='REVIEW_UNAVAILABLE_OLD_VIDEO'?'レビュー不能':r.reviewed?'確認済み':'未確認'}</span></button>`).join('')}</details>`}).join('')||'<p>対象レースはありません。</p>';for(const b of $('races').querySelectorAll('button'))b.onclick=()=>openRace(b.dataset.race).catch(notify)}async function list(append=false){const d=await api(`/api/races?reviewer=${encodeURIComponent(reviewer())}&pending=${pending?1:0}&includeUnavailable=${$('show-unavailable').checked?1:0}&offset=${append?nextOffset:0}`);allRows=append?[...allRows,...d.rows]:d.rows;nextOffset=d.nextOffset;$('more').hidden=nextOffset===null;renderList()}
const opts=(rs,unknown=true)=>`${unknown?'<option value="UNKNOWN">不明</option>':''}${rs.map(r=>`<option value="${esc(r.riderId)}">${r.number}番 ${esc(r.name||r.riderId)}</option>`).join('')}`;const radios=(name,values)=>values.map(([v,l])=>`<label class="radio"><input type="radio" name="${name}" value="${v}">${l}</label>`).join('');const q=(title,desc,body)=>`<section class="question"><h2>${title}</h2><p>${desc}</p>${body}</section>`;const who=(id,c)=>{const r=c.riders.find(x=>x.riderId===id);return r?`${r.number}番 ${r.name||''}選手`:'選択した選手'};
async function openRace(key){current=await api(`/api/race/${encodeURIComponent(key)}?reviewer=${encodeURIComponent(reviewer())}`);const c=current.reviewCaseV2,done=Boolean(current.priorReviewV2),blocked=current.availability==='REVIEW_UNAVAILABLE_OLD_VIDEO',search=encodeURIComponent(searchQuery(current.record)),out=[['RESERVED','余力を残していた'],['NO_CLEAR_DECELERATION','大きな失速はなかった'],['CLEAR_DECELERATION','明確に失速した'],['UNKNOWN','不明']];$('review').innerHTML=`<h1>${raceDate(key)} ${esc(current.record.venueName)} ${current.record.raceNo}R</h1><p><b>Manual Review V2 / ${c.mode==='GIRLS'?'ガールズ':'男子'}</b>　${blocked?'レビュー不能（古いレース・公式映像なし）':done?'確認済み':'未確認'}</p><div class="video-links"><a href="https://www.google.com/search?q=${search}" target="_blank">映像を探す ↗</a>${current.record.officialVideoUrls.map(u=>`<a href="${esc(u)}" target="_blank">公式映像を見る ↗</a>`).join('')}</div><form id="v2form">
${q('Q1 最終バックを先頭で通過した選手は誰？','最初に仕掛けた選手ではなく、最終バック線を先頭で通過した選手。',`<select name="backLeaderRiderId">${opts(c.riders)}</select>`)}
${q('Q2 最終バックまでに、先頭で駆ける選手の交代はあった？','一瞬前へ出ただけでなく、先頭で駆ける役割が移ったか。',radios('leaderTurnover',[['NONE','なし'],['OCCURRED','あり'],['UNKNOWN','不明']]))}
${q('Q3 Q1選手より前に、長く先頭で駆けた選手はいた？','一定区間レースを引っ張った選手。厳密な秒数計測は不要。',radios('longLeader',[['NONE','いない'],['PRESENT','いる'],['UNKNOWN','不明']])+`<div id="long-rider" hidden><select name="longLeaderRiderId">${opts(c.riders,false)}</select></div>`)}
<section class="question" id="q4" hidden><h2>Q4 <span id="q4target">Q3選手</span>は、その後どうなった？</h2><p>Q3で選んだ選手について回答してください。</p>${radios('longLeaderOutcome',out)}</section>
${q('Q5 <span class="q1target">Q1の最終バック先頭選手</span>は、その後どうなった？','Q1で選んだ選手について回答してください。',radios('backLeaderOutcome',out))}
${c.mode==='STANDARD'?`${q('Q6 <span class="q1target">Q1選手</span>の番手は誰？','Q1選手のラインの番手を人の観測として選択。',radios('banteStatus',[['NONE','番手なし'],['UNKNOWN','不明'],['RIDER','選手を指定']])+`<div id="bante-rider" hidden><select name="banteRiderId">${opts(c.riders,false)}</select></div>`)}<section class="question" id="q7" hidden><h2>Q7 <span id="q7target">番手選手</span>はどう動いた？</h2><p>必ずQ1選手のラインの番手について回答。</p>${radios('banteAction',[['SUPPORTED_FRONT','前を援護した'],['HELD_POSITION','番手を維持した'],['SELF_LAUNCHED','自分で踏み出した'],['SWITCHED','別ライン・別選手へ切り替えた'],['SEPARATED','前についていけず離れた'],['UNKNOWN','不明']])}</section>${q('Q8 最終バック付近で<span class="q1target">Q1選手</span>のラインはどうなっていた？','Q1で選んだ選手のラインについて回答。',radios('lineState',[['INTACT','ライン維持'],['PARTIAL_BREAK','一部崩れ'],['COLLAPSED','完全に崩れ'],['UNKNOWN','不明']]))}`:''}
${q(c.mode==='GIRLS'?'G6 最終4角〜直線入口で、他選手が着争い可能位置に残っていた？':'Q9 最終4角〜直線入口で、別ラインから着争い可能位置に残っていた選手はいた？','最終着順ではなく、その時点で上位争いに加われる位置にいたか。',radios('otherContenders',[['NONE','いない'],['PRESENT','いる'],['UNKNOWN','不明']])+`<div id="other-riders" hidden>${c.riders.map(r=>`<label class="radio"><input type="checkbox" name="otherContenderRiderIds" value="${esc(r.riderId)}">${r.number}番 ${esc(r.name||r.riderId)}</label>`).join('')}</div>`)}
${q('Q10 映像だけでは判断できなかった点はある？','不明回答の説明は必須ではありません。',radios('uncertainty',[['NONE','なし'],['PRESENT','あり']])+'<input id="uncertainty-note" name="uncertaintyNote" hidden placeholder="任意メモ">')}
<div class="evidence"><input name="evidenceSource" placeholder="映像URL・確認時刻、または独立観測メモ"><label><input type="checkbox" name="independentEvidence">映像・独立観測で確認した</label></div><div class="actions"><button type="button" id="unknown-all">判断項目をすべて不明</button><button class="primary" ${done||blocked?'disabled':''}>保存して次へ</button></div></form>`;wire(c)}
function wire(c){const f=$('v2form'),show=()=>{const q1=who(f.elements.backLeaderRiderId.value,c);for(const x of f.querySelectorAll('.q1target'))x.textContent=q1;const long=f.elements.longLeader?.value==='PRESENT';$('long-rider').hidden=!long;$('q4').hidden=!long;if(long)$('q4target').textContent=who(f.elements.longLeaderRiderId.value,c);if(c.mode==='STANDARD'){const b=f.elements.banteStatus?.value==='RIDER';$('bante-rider').hidden=!b;$('q7').hidden=!b;if(b)$('q7target').textContent=who(f.elements.banteRiderId.value,c)}$('other-riders').hidden=f.elements.otherContenders?.value!=='PRESENT';$('uncertainty-note').hidden=f.elements.uncertainty?.value!=='PRESENT'};f.onchange=show;$('unknown-all').onclick=()=>{for(const n of ['leaderTurnover','longLeader','backLeaderOutcome','banteStatus','lineState','otherContenders']){const x=f.querySelector(`[name=${n}][value=UNKNOWN]`);if(x)x.checked=true}f.elements.backLeaderRiderId.value='UNKNOWN';show()};f.onsubmit=e=>{e.preventDefault();save(new FormData(f)).catch(notify)}}
async function save(fd){if(!reviewer())throw Error('確認者IDを入力してください。');const one=n=>fd.get(n)||'UNKNOWN',answers={backLeaderRiderId:one('backLeaderRiderId'),leaderTurnover:one('leaderTurnover'),longLeader:one('longLeader'),longLeaderRiderId:one('longLeaderRiderId'),longLeaderOutcome:one('longLeaderOutcome'),backLeaderOutcome:one('backLeaderOutcome'),banteStatus:one('banteStatus'),banteRiderId:one('banteRiderId'),banteAction:one('banteAction'),lineState:one('lineState'),otherContenders:one('otherContenders'),otherContenderRiderIds:fd.getAll('otherContenderRiderIds'),uncertainty:fd.get('uncertainty')||'NONE',uncertaintyNote:fd.get('uncertaintyNote')||''};const old=current.raceKey;await api('/api/review',{method:'POST',headers:{'content-type':'application/json','x-research-review':'1'},body:JSON.stringify({manualReviewVersion:2,raceKey:old,reviewerId:reviewer(),answers,evidenceSource:fd.get('evidenceSource'),independentEvidence:fd.get('independentEvidence')==='on'})});notify('保存しました');await list();const next=nextPendingRace(allRows,old);if(next)await openRace(next.raceKey);else $('review').innerHTML='<h1>未確認レースはありません</h1>'}
$('period').onchange=renderList;$('show-unavailable').onchange=()=>list().catch(notify);$('reviewer').onchange=()=>{localStorage.setItem('action-reviewer',reviewer());list().catch(notify)};$('pending').onclick=()=>{pending=true;list().catch(notify)};$('all').onclick=()=>{pending=false;list().catch(notify)};$('more').onclick=()=>list(true).catch(notify);$('refresh').onclick=()=>Promise.all([status(),list()]).catch(notify);try{await Promise.all([status(),list()])}catch(e){notify(e)}
