import crypto from "node:crypto";
import {reweightExistingResearch,WEIGHT_GRID,RELATIVE_CANDIDATE_ID} from "./candidate.mjs";
import {aggregate} from "../db-baseline/backtest.mjs";

export function runRelativeBacktest(records){const ordered=[...records].filter(valid).sort(order).slice(0,302);if(ordered.length!==302)throw Error(`DEVELOPMENT_COHORT_INCOMPLETE:${ordered.length}/302`);const baseline=ordered.map(x=>evaluate(x.research.terminals,x.result.finishOrder));
  const specs={R1:["racePointDiff"],R2:["winRateDiff"],R3:["HBDiff"],R4:["sprintFinishDiff"]},runs={R0:reportRun(ordered,baseline,baseline,{})},search={};const selected={};
  for(const[name,features]of Object.entries(specs)){const trials=gridTrials(ordered,baseline,features);search[name]=trials.map(compactTrial);runs[name]=best(trials);selected[features[0]]=runs[name].weights[features[0]];}
  const useful=Object.fromEntries(Object.entries(selected).filter(([,w])=>w!==0)),r5Trials=gridTrials(ordered,baseline,Object.keys(useful).slice(0,2));search.R5=r5Trials.map(compactTrial);runs.R5=best(r5Trials);const firstWeights=runs.R5.weights;
  const r6Trials=WEIGHT_GRID.map(w=>run(ordered,baseline,{...firstWeights,trackingDiff:w})),r7Trials=WEIGHT_GRID.map(w=>run(ordered,baseline,{...firstWeights,sameLineRole:w}));search.R6=r6Trials.map(compactTrial);search.R7=r7Trials.map(compactTrial);runs.R6=best(r6Trials);runs.R7=best(r7Trials);
  const r8Trials=WEIGHT_GRID.flatMap(t=>WEIGHT_GRID.map(s=>run(ordered,baseline,{...firstWeights,trackingDiff:t,sameLineRole:s})));search.R8=r8Trials.map(compactTrial);runs.R8=best(r8Trials);
  const featureClassification=classify(runs),candidate=guard(runs.R0,runs.R8);
  return{candidateId:candidate.accepted?RELATIVE_CANDIDATE_ID:null,status:candidate.accepted?"ACCEPTED_FOR_SHADOW":"NO_CANDIDATE",classification:candidate.accepted?"SHADOW_CANDIDATE_ONLY":null,productionWriteAllowed:false,autoPromotion:false,development:{count:302,split:{early:"1-213",late:"214-302"},raceKeys:ordered.map(x=>x.raceKey),trainingHash:hash(ordered.map(x=>x.raceKey)),validation303To402Touched:false,final403To502Touched:false},runs,gridSearch:search,featureClassification,candidateDecision:candidate,behaviorTraitStatus:"BEHAVIOR_TRAITS_NOT_ENOUGH_DATA"};}

function gridTrials(records,baseline,features){if(!features.length)return[run(records,baseline,{})];let sets=[{}];for(const f of features)sets=sets.flatMap(x=>WEIGHT_GRID.map(w=>({...x,[f]:w})));return sets.map(w=>run(records,baseline,w))}
function run(records,baseline,weights){const rows=records.map(x=>evaluate(reweightExistingResearch({race:x.preRaceInput.race,terminals:x.research.terminals,weights}).terminals,x.result.finishOrder));return reportRun(records,baseline,rows,weights)}
function reportRun(records,base,rows,weights){return{weights,overall:aggregate(rows),early:aggregate(rows.slice(0,213)),late:aggregate(rows.slice(213)),h2h:h2h(base,rows),tail:tail(base,rows),raceDeltas:rows.map((x,i)=>({raceKey:records[i].raceKey,exactRank:x.exactRank,baselineRank:base[i].exactRank,delta:x.exactRank-base[i].exactRank,firstRank:x.firstRank,pairRank:x.pairRank}))}}
function best(runs){return[...runs].sort((a,b)=>score(b)-score(a)||a.overall.exactMeanRank-b.overall.exactMeanRank||weightSize(a.weights)-weightSize(b.weights))[0]}
function score(x){const o=x.overall,e=x.early,l=x.late;return-(o.exactMeanRank*2)+o.mrr*100+o.firstTop3*30+o.pairTop3*30+o.pairTop5*20-(Math.max(0,e.exactMeanRank-60)+Math.max(0,l.exactMeanRank-60))}
function compactTrial(x){return{weights:x.weights,overall:x.overall,earlyMeanRank:x.early.exactMeanRank,lateMeanRank:x.late.exactMeanRank,h2h:x.h2h,tail:x.tail}}
function classify(runs){const map={racePointDiff:"R1",winRateDiff:"R2",HBDiff:"R3",sprintFinishDiff:"R4",trackingDiff:"R6",sameLineRole:"R7"},base=runs.R0.overall;return Object.fromEntries(Object.entries(map).map(([f,r])=>{const x=runs[r];const early=x.early.exactMeanRank<=runs.R0.early.exactMeanRank,late=x.late.exactMeanRank<=runs.R0.late.exactMeanRank,unchanged=x.overall.exactMeanRank===base.exactMeanRank&&x.overall.mrr===base.mrr,value=x.weights[f]===0||unchanged?"NEUTRAL":x.overall.exactMeanRank<base.exactMeanRank&&early&&late?"USEFUL":x.overall.exactMeanRank>base.exactMeanRank?"HARMFUL":"INSUFFICIENT";return[f,{classification:value,selectedWeight:unchanged?0:(x.weights[f]||0),earlyDirection:early,lateDirection:late}] }))}
function guard(base,c){const b=base.overall,x=c.overall,t=c.tail,checks={firstTop1:x.firstTop1>=b.firstTop1-.005,firstTop3:x.firstTop3>=b.firstTop3,pairTop3:x.pairTop3>=b.pairTop3,pairTop5:x.pairTop5>=b.pairTop5,mean:x.exactMeanRank<=b.exactMeanRank,mrr:x.mrr>=b.mrr-.01,top20:x.top20>=b.top20-.02,tail30:t.worsening30Plus<=15,tail50:t.worsening50Plus<=8,worst:t.worstDelta<183,direction:c.early.exactMeanRank<=base.early.exactMeanRank&&c.late.exactMeanRank<=base.late.exactMeanRank};return{accepted:Object.values(checks).every(Boolean),checks,weights:c.weights}}
function evaluate(ledger,result){const order=result.slice(0,3).map(Number),rows=[...ledger].sort((a,b)=>Number(b.terminalProbability)-Number(a.terminalProbability)||a.order.join("-").localeCompare(b.order.join("-"),"en")),exact=rows.findIndex(x=>same(x.order,order))+1,first=rank(group(rows,x=>`${x.order[0]}`),`${order[0]}`),pair=rank(group(rows,x=>`${x.order[0]}-${x.order[1]}`),`${order[0]}-${order[1]}`),third=rank(group(rows.filter(x=>+x.order[0]===order[0]&&+x.order[1]===order[1]),x=>`${x.order[2]}`),`${order[2]}`);return{exactRank:exact||Infinity,firstRank:first,pairRank:pair,thirdRank:third}}
function group(rows,key){const m=new Map();for(const x of rows)m.set(key(x),(m.get(key(x))||0)+Number(x.terminalProbability||0));return[...m].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],"en"))}function rank(a,k){const i=a.findIndex(x=>x[0]===k);return i<0?Infinity:i+1}function same(a,b){return a.slice(0,3).map(Number).join("-")===b.join("-")}
function h2h(a,b){let candidate=0,existing=0,tie=0;b.forEach((x,i)=>x.exactRank<a[i].exactRank?candidate++:x.exactRank>a[i].exactRank?existing++:tie++);return{candidate,existing,tie}}
function tail(a,b){const d=b.map((x,i)=>x.exactRank-a[i].exactRank).sort((x,y)=>x-y);return{worsening30Plus:d.filter(x=>x>=30).length,worsening50Plus:d.filter(x=>x>=50).length,worsening100Plus:d.filter(x=>x>=100).length,worstDelta:d.at(-1),p10Delta:d[Math.ceil(d.length*.9)-1]}}
function valid(x){return x?.state==="COMPARED"&&x?.research?.terminals&&x?.result?.status==="confirmed"}function order(a,b){return Date.parse(a.comparedAt)-Date.parse(b.comparedAt)||a.raceKey.localeCompare(b.raceKey,"en")}function hash(keys){return crypto.createHash("sha256").update(keys.join("\n")).digest("hex")}
function weightSize(weights){return Object.values(weights||{}).reduce((n,x)=>n+Math.abs(Number(x)||0),0)}
