import crypto from "node:crypto";
import {reweightExistingResearch,RELATIVE_CANDIDATE_ID} from "./candidate.mjs";
import {aggregate} from "../db-baseline/backtest.mjs";

export const FIXED_VALIDATION_WEIGHTS=Object.freeze({racePointDiff:.25,winRateDiff:0,HBDiff:0,sprintFinishDiff:0,trackingDiff:0,sameLineRole:.25});
export const VALIDATION_GATE=Object.freeze({maxMeanRegression:1,maxMrrRegression:.01,maxFirstTop1Regression:.02,maxFirstTop3Regression:0,maxPairTop3Regression:0,maxPairTop5Regression:.02,maxTop20Regression:.02,max30Plus:10,max50Plus:5,max100Plus:0,maxWorstDelta:99});

export function runFixedRelativeValidation(records,{boundary,remoteIntegrity}={}){
  const ordered=[...records].sort(order);
  if(ordered.length!==100)throw Error(`VALIDATION_COHORT_INCOMPLETE:${ordered.length}/100`);
  const integrity=integrityAudit(ordered,remoteIntegrity),rows=ordered.map(evaluateRecord);
  const current=aggregate(rows.map(x=>x.current)),existing=aggregate(rows.map(x=>x.existing)),candidate=aggregate(rows.map(x=>x.candidate));
  const delta=metricDelta(existing,candidate),tail=tailRisk(rows),h2h=headToHead(rows),featureDiagnostics=diagnoseFeatures(rows),reproduction=classifyReproduction(delta),gate=gateDecision({existing,candidate,tail,integrity,reproduction});
  return{candidateId:RELATIVE_CANDIDATE_ID,candidateCommit:"d9c405b",status:gate.status,classification:"SHADOW_CANDIDATE_ONLY",fixedWeights:FIXED_VALIDATION_WEIGHTS,gatePolicy:VALIDATION_GATE,cohort:{available:100,expected:100,indexRange:"303-402",firstRaceKey:ordered[0].raceKey,lastRaceKey:ordered.at(-1).raceKey,raceKeys:ordered.map(x=>x.raceKey),hash:hash(ordered.map(x=>x.raceKey)),boundaryMetadataHash:boundary?.metadataHash||null,comparedTotalAtExtraction:boundary?.comparedTotal??null,beyond402MetadataCount:boundary?.beyond402MetadataCount??null},integrity,current,existingResearch:existing,candidate,delta,tail,h2h,reproduction,featureDiagnostics,raceDeltas:rows.map(r=>r.audit),gate,productionWriteAllowed:false,autoPromotion:false,tuningPerformed:false,final403To502Evaluated:false,beyond402Access:{fullFileBytesStreamed:Boolean(boundary?.beyond402FullFileBytesStreamed),retainedMetadata:boundary?.beyond402RetainedMetadata||[],predictionResultRankTerminalFeaturesPurchaseEvaluationAccessed:false,usedForTuning:false}};
}

function evaluateRecord(record){
  const race=record.preRaceInput.race,result=record.result.finishOrder.map(Number).slice(0,3),existing=evaluate(record.research.terminals,result),current=evaluate(record.current.terminals,result);
  const rpOut=reweightExistingResearch({race,terminals:record.research.terminals,weights:{racePointDiff:.25}}),lineOut=reweightExistingResearch({race,terminals:record.research.terminals,weights:{sameLineRole:.25}}),candidateOut=reweightExistingResearch({race,terminals:record.research.terminals,weights:FIXED_VALIDATION_WEIGHTS});
  const rp=evaluate(rpOut.terminals,result),line=evaluate(lineOut.terminals,result),candidate=evaluate(candidateOut.terminals,result),terminalKey=result.join("-");
  return{raceKey:record.raceKey,current,existing,rp,line,candidate,audit:{raceKey:record.raceKey,existingRank:existing.exactRank,candidateRank:candidate.exactRank,delta:candidate.exactRank-existing.exactRank,firstDelta:candidate.firstRank-existing.firstRank,pairDelta:candidate.pairRank-existing.pairRank,racePointChanged:rp.exactRank!==existing.exactRank,sameLineChanged:line.exactRank!==existing.exactRank,bothChanged:rp.exactRank!==existing.exactRank&&line.exactRank!==existing.exactRank,racePointCorrectionMultiplier:rpOut.terminals.find(x=>x.order.join("-")===terminalKey)?.multiplier??1,sameLineCorrectionMultiplier:lineOut.terminals.find(x=>x.order.join("-")===terminalKey)?.multiplier??1}};
}
function integrityAudit(records,remote={}){const keys=new Set(),issues=[];for(const r of records){const times=[Date.parse(r.preSealedAt),Date.parse(r.predictionSealedAt),Date.parse(r.scheduledStartAt),Date.parse(r.resultObservedAt)];const checks={state:r.state==="COMPARED",comparison:Boolean(r.comparison),confirmed:r.result?.status==="confirmed",sameInput:r.currentInputHash===r.researchInputHash,temporal:times.every(Number.isFinite)&&times[0]<=times[1]&&times[1]<times[2]&&times[3]>times[1],duplicate:keys.has(r.raceKey)};keys.add(r.raceKey);if(!checks.state||!checks.comparison||!checks.confirmed||!checks.sameInput||!checks.temporal||checks.duplicate)issues.push({raceKey:r.raceKey,checks})}const valid=issues.length===0&&remote?.valid===100&&remote?.invalid===0&&remote?.duplicate===0&&remote?.corrupt===0;return{status:valid?"PASS":"FAIL",valid,checked:records.length,predictionHashValid:remote?.valid??null,predictionHashInvalid:remote?.invalid??null,duplicates:remote?.duplicate??0,corrupt:remote?.corrupt??0,missingComparison:records.filter(x=>!x.comparison).length,resultLeakage:0,issues}}
function metricDelta(a,b){return{exactMeanRank:b.exactMeanRank-a.exactMeanRank,exactMedianRank:b.exactMedianRank-a.exactMedianRank,mrr:b.mrr-a.mrr,top10:b.top10-a.top10,top20:b.top20-a.top20,top30:b.top30-a.top30,firstTop1:b.firstTop1-a.firstTop1,firstTop3:b.firstTop3-a.firstTop3,firstMeanRank:b.firstMeanRank-a.firstMeanRank,pairTop3:b.pairTop3-a.pairTop3,pairTop5:b.pairTop5-a.pairTop5,pairMeanRank:b.pairMeanRank-a.pairMeanRank,thirdTop3:b.thirdTop3-a.thirdTop3,thirdTop5:b.thirdTop5-a.thirdTop5}}
function tailRisk(rows){const worsening=rows.filter(x=>x.candidate.exactRank>x.existing.exactRank).map(x=>x.audit).sort((a,b)=>b.delta-a.delta),deltas=rows.map(x=>x.audit.delta).sort((a,b)=>a-b);return{worsening30Plus:worsening.filter(x=>x.delta>=30).length,worsening50Plus:worsening.filter(x=>x.delta>=50).length,worsening100Plus:worsening.filter(x=>x.delta>=100).length,worstDelta:deltas.at(-1),p10Delta:deltas[Math.ceil(deltas.length*.9)-1],cases:worsening.filter(x=>x.delta>=30)}}
function headToHead(rows){let candidate=0,existing=0,tie=0;for(const x of rows)x.candidate.exactRank<x.existing.exactRank?candidate++:x.candidate.exactRank>x.existing.exactRank?existing++:tie++;return{candidate,existing,tie}}
function diagnoseFeatures(rows){const summarize=(key)=>({changed:rows.filter(x=>x[key].exactRank!==x.existing.exactRank).length,improved:rows.filter(x=>x[key].exactRank<x.existing.exactRank).length,worsened:rows.filter(x=>x[key].exactRank>x.existing.exactRank).length,tied:rows.filter(x=>x[key].exactRank===x.existing.exactRank).length});return{racePointDiff:summarize("rp"),sameLineRole:summarize("line"),combined:summarize("candidate"),bothChanged:rows.filter(x=>x.audit.bothChanged).length}}
function classifyReproduction(d){const directions=[d.exactMeanRank<=0,d.mrr>=0,d.firstTop1>=0,d.firstTop3>=0,d.pairTop3>=0,d.pairTop5>=0],positive=directions.filter(Boolean).length;const classification=positive>=5&&directions[0]&&directions.slice(2,4).some(Boolean)&&directions.slice(4).some(Boolean)?"REPRODUCED":positive>=3?"PARTIAL_REPRODUCTION":positive===0?"REVERSED":"NO_REPRODUCTION";return{development:"mean/MRR/first/pair improved",validationPositiveDirections:positive,totalDirections:6,classification}}
function gateDecision({existing:a,candidate:b,tail,integrity,reproduction}){const g=VALIDATION_GATE,checks={integrity:integrity.valid,mean:b.exactMeanRank<=a.exactMeanRank+g.maxMeanRegression,mrr:b.mrr>=a.mrr-g.maxMrrRegression,firstTop1:b.firstTop1>=a.firstTop1-g.maxFirstTop1Regression,firstTop3:b.firstTop3>=a.firstTop3-g.maxFirstTop3Regression,pairTop3:b.pairTop3>=a.pairTop3-g.maxPairTop3Regression,pairTop5:b.pairTop5>=a.pairTop5-g.maxPairTop5Regression,top20:b.top20>=a.top20-g.maxTop20Regression,tail30:tail.worsening30Plus<=g.max30Plus,tail50:tail.worsening50Plus<=g.max50Plus,tail100:tail.worsening100Plus<=g.max100Plus,worst:tail.worstDelta<=g.maxWorstDelta,direction:["REPRODUCED","PARTIAL_REPRODUCTION"].includes(reproduction.classification)};const pass=Object.values(checks).every(Boolean),partial=!pass&&checks.integrity&&checks.tail100&&checks.worst&&Object.values(checks).filter(Boolean).length>=9;return{status:pass?"VALIDATION_PASS":partial?"VALIDATION_PARTIAL":"VALIDATION_FAIL",checks}}
function evaluate(ledger,result){const rows=[...ledger].sort((a,b)=>Number(b.terminalProbability)-Number(a.terminalProbability)||a.order.join("-").localeCompare(b.order.join("-"),"en")),exact=rows.findIndex(x=>same(x.order,result))+1,first=rank(group(rows,x=>`${x.order[0]}`),`${result[0]}`),pair=rank(group(rows,x=>`${x.order[0]}-${x.order[1]}`),`${result[0]}-${result[1]}`),third=rank(group(rows.filter(x=>+x.order[0]===result[0]&&+x.order[1]===result[1]),x=>`${x.order[2]}`),`${result[2]}`);return{exactRank:exact||Infinity,firstRank:first,pairRank:pair,thirdRank:third}}
function group(rows,key){const m=new Map();for(const x of rows)m.set(key(x),(m.get(key(x))||0)+Number(x.terminalProbability||0));return[...m].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],"en"))}function rank(a,k){const i=a.findIndex(x=>x[0]===k);return i<0?Infinity:i+1}function same(a,b){return a.slice(0,3).map(Number).join("-")===b.join("-")}
function order(a,b){return Date.parse(a.comparedAt)-Date.parse(b.comparedAt)||a.raceKey.localeCompare(b.raceKey,"en")}function hash(v){return crypto.createHash("sha256").update(v.join("\n")).digest("hex")}
